include:
  - immich.yml

services:

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    environment:
      - JELLYFIN_PublishedServerUrl=http://192.168.16.11:8096
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /wrigley/data/jellyfin:/config
      - /wrigley/data/jellyfin-cache:/cache
      - /weeghman/media/music:/media/music
      - /weeghman/media/movies:/media/movies
      - /weeghman/media/tv:/media/tv
    ports:
      - 8096:8096
      - 7359:7359/udp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  whisper:
    image: lscr.io/linuxserver/faster-whisper:gpu-v2.3.0-ls49
    container_name: whisper
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Americas/Chicago
      - WHISPER_MODEL=medium-int8
      - WHISPER_BEAM=5
    volumes:
      - /wrigley/data/whisper:/config
    ports:
      - 10300:10300
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
